---
- name: Apply changes to kubernetes
  hosts: localhost
  remote_user: ansible
  become: false
  tasks:
    - name: Print the working directory from where the playbook was run
      debug:
        msg: "Playbook was executed from: {{ ansible_env.PWD }} with user {{ ansible_user}}"
    - name: Print kube config
      debug:
        msg: "File content: {{ lookup('file', '/kube-config/.kube/config') }}"
    - name: Apply deployment
      environment:
        KUBECONFIG: "/kube-config/.kube/config"
      k8s:
        kubeconfig: "/kube-config/.kube/config"
        state: present
        namespace: default
        src: frontend-deployment.yaml
    - name: Apply service
      k8s:
        kubeconfig: /home/shrutik/.kube/config
        state: present
        namespace: default
        src: frontend-service.yaml
    - name: Apply networking
      k8s:
        kubeconfig: /home/shrutik/.kube/config
        state: present
        namespace: default
        src: frontend-networking.yaml
