---
- name: Apply changes to kubernetes
  hosts: localhost
  remote_user: shrutik15
  become: false
  tasks:
    - name: Print the working directory from where the playbook was run
      debug:
        msg: "Playbook was executed from: {{ ansible_env.PWD }} with user {{ ansible_user}}"
    - name: Apply deployment
      environment:
        KUBECONFIG: ~/.kube/config
      k8s:
        kubeconfig: ~/.kube/config
        state: present
        namespace: default
        src: frontend-deployment.yaml
    - name: Apply service
      k8s:
        state: present
        namespace: default
        src: frontend-service.yaml
    - name: Apply networking
      k8s:
        state: present
        namespace: default
        src: frontend-networking.yaml
