---
- name: Apply changes to kubernetes
  hosts: localhost
  remote_user: shrutik15
  become: false
  tasks:
    - name: Print the working directory from where the playbook was run
      debug:
        msg: "Playbook was executed from: {{ ansible_env.PWD }}"
    - name: Apply deployment
      command: kubectl apply -f "{{ ansible_env.PWD }}/frontend-deployment.yaml" --validate=false
      become: yes
    - name: Apply service
      shell: kubectl apply -f frontend-service.yaml --validate=false
    - name: Apply networking
      shell: kubectl apply -f frontend-networking.yaml --validate=false

