---
- name: Apply changes to kubernetes
  hosts: localhost
  remote_user: shrutik15
  become: false
  tasks:
    - name: Apply deployment
      shell: kubectl apply -f --validate=false frontend-deployment.yaml
    - name: Apply service
      shell: kubectl apply -f --validate=false frontend-service.yaml
    - name: Apply networking
      shell: kubectl apply -f --validate=false frontend-networking.yaml

